<?php

use Illuminate\Database\Seeder;

class BilansTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {	
    	//2010
        DB::table('bilans')->insert([
        	'company_id' => 1,
        	'year' => 2010,
        	'cap_sous_na' => 0,
			'frais_etab' => 0,
			'frais_dev' => 0,
			'concess' => 1224,
			'fds_comm' => 0,
			'autres_imm_inco' => 0,
			'avac_imm_inco' => 0,
			'terrains' => 0,
			'construc' => 0,
			'mat_indus' => 24537,
			'autres_imm_co' => 135459,
			'imm_en_cours' => 0,
			'avac_imm_co' => 0,
			'part_equiv' => 0,
			'autres_part' => 0,
			'creances_part' => 0,
			'autres_titres_imm' => 0,
			'prets' => 0,
			'autres_imm_fi' => 16093,
			'mp_appro' => 70585,
			'encours_prod_biens' => 0,
			'encours_prod_services' => 0,
			'prod_interm_fin' => 0,
			'marchand' => 0,
			'avac_comm' => 5850,
			'creances_clients' => 1292042,
			'autres_creances' => 349100,
			'cap_sous_a_nv' => 0,
			'val_mob' => 841022,
			'dispo' => 210150,
			'charges_ca' => 21795,
			'frais_emm_emp_et' => 0,
			'primes_remb_oblig' => 0,
			'ecart_conv_actif' => 0,
			'cap_soc_indiv' => 100000,
			'primes_fus_emm_ap' => 0,
			'ecart_reeval' => 0,
			'res_leg' => 10000,
			'res_stat_contract' => 0,
			'res_reg' => 0,
			'autres_res' => 568015,
			'report_anouv' => 0,
			'result_ex' => 779186,
			'sub_invest' => 0,
			'prov_reg' => 0,
			'prod_emm_part' => 0,
			'av_condt' => 0,
			'prov_risques' => 0,
			'prov_charges' => 0,
			'emp_oblig_conv' => 0,
			'autres_emp_oblig' => 0,
			'emprunt_etab_credit' => 289,
			'dette_fi_div' => 217634,
			'avac_rec_comm' => 0,
			'dette_fourn' => 686042,
			'dette_fisc' => 602738,
			'dette_immo' => 1052,
			'autres_dettes' => 2900,
			'prod_ca' => 0,
			'ecart_conv_pass' => 0,
    	]);

        //2009
    	DB::table('bilans')->insert([
        	'company_id' => 1,
        	'year' => 2009,
        	'cap_sous_na' => 0,
			'frais_etab' => 0,
			'frais_dev' => 0,
			'concess' => 0,
			'fds_comm' => 0,
			'autres_imm_inco' => 0,
			'avac_imm_inco' => 0,
			'terrains' => 0,
			'construc' => 0,
			'mat_indus' => 34060,
			'autres_imm_co' => 123831,
			'imm_en_cours' => 0,
			'avac_imm_co' => 0,
			'part_equiv' => 0,
			'autres_part' => 0,
			'creances_part' => 0,
			'autres_titres_imm' => 0,
			'prets' => 0,
			'autres_imm_fi' => 16298,
			'mp_appro' => 66680,
			'encours_prod_biens' => 0,
			'encours_prod_services' => 0,
			'prod_interm_fin' => 0,
			'marchand' => 0,
			'avac_comm' => 350,
			'creances_clients' => 978492,
			'autres_creances' => 41429,
			'cap_sous_a_nv' => 0,
			'val_mob' => 1969592,
			'dispo' => 235400,
			'charges_ca' => 22936,
			'frais_emm_emp_et' => 0,
			'primes_remb_oblig' => 0,
			'ecart_conv_actif' => 0,
			'cap_soc_indiv' => 100000,
			'primes_fus_emm_ap' => 0,
			'ecart_reeval' => 0,
			'res_leg' => 10000,
			'res_stat_contract' => 0,
			'res_reg' => 0,
			'autres_res' => 218514,
			'report_anouv' => 0,
			'result_ex' => 1349501,
			'sub_invest' => 0,
			'prov_reg' => 0,
			'prod_emm_part' => 0,
			'av_condt' => 0,
			'prov_risques' => 0,
			'prov_charges' => 0,
			'emp_oblig_conv' => 0,
			'autres_emp_oblig' => 0,
			'emprunt_etab_credit' => 674,
			'dette_fi_div' => 209044,
			'avac_rec_comm' => 29897,
			'dette_fourn' => 843744,
			'dette_fisc' => 727693,
			'dette_immo' => 0,
			'autres_dettes' => 0,
			'prod_ca' => 0,
			'ecart_conv_pass' => 0,
    	]);
    }
}
