<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Balance fields of the App
    |--------------------------------------------------------------------------
    |
    |
    |
    */

    'bilan_fields' => [
        'cap_sous_na' => 'Capital souscrit non appelé',
        'frais_etab' => 'Frais d\'établissement',
        'frais_dev' => 'Frais de développement',
        'concess' => 'Concessions, brevets et droits similaires',
        'fds_comm' => 'Fonds commercial',
        'autres_imm_inco' => 'Autres immobilisations incorporelles',
        'avac_imm_inco' => 'Avances et acomptes sur immobilisations incorporelles',
        'terrains' => 'Terrains',
        'construc' => 'Constructions',
        'mat_indus' => 'Installations techniques, matériel et outillage industriels',
        'autres_imm_co' => 'Autres immobilisations corporelles',
        'imm_en_cours' => 'Immobilisations en cours',
        'avac_imm_co' => 'Avances et acomptes',
        'part_equiv' => 'Participations évaluées selon la méthode de mise en équivalence',
        'autres_part' => 'Autres participations',
        'creances_part' => 'Créances rattachées à des participations',
        'autres_titres_imm' => 'Autres titres immobilisés',
        'prets' => 'Prêts',
        'autres_imm_fi' => 'Autres immobilisations financières',
        'mp_appro' => 'Matières premières, approvisionnements',
        'encours_prod_biens' => 'En cours de production de biens',
        'encours_prod_services' => 'En cours de production de services',
        'prod_interm_fin' => 'Produits intermédiaires et finis',
        'marchand' => 'Marchandise',
        'avac_comm' => 'Avances et acomptes versés sur commandes',
        'creances_clients' => 'Clients et comptes rattachés',
        'autres_creances' => 'Autres créances',
        'cap_sous_a_nv' => 'Capital souscrit et appelé, non versé',
        'val_mob' => 'Valeurs mobilières de placement',
        'dispo' => 'Disponibilités',
        'charges_ca' => 'Charges constatées d\'avance',
        'frais_emm_emp_et' => 'Frais d\'émission d\'emprunt à étaler',
        'primes_remb_oblig' => 'Primes de remboursement des obligations',
        'ecart_conv_actif' => 'Ecarts de conversion actif',
        'cap_soc_indiv' => 'Capital social ou individuel',
        'primes_fus_emm_ap' => 'Primes d\'émission, de fusion, d\'apport',
        'ecart_reeval' => 'Ecart de réévaluation',
        'res_leg' => 'Réserve légale',
        'res_stat_contract' => 'Réserves statuaires ou contractuelles',
        'res_reg' => 'Réserves réglementées',
        'autres_res' => 'Autres réserves',
        'report_anouv' => 'Report à nouveau',
        'result_ex' => 'RESULTAT DE L\'EXERCICE',
        'sub_invest' => 'Subventions d\'investissement',
        'prov_reg' => 'Provision réglementées',
        'prod_emm_part' => 'Produit des émissions de titres participatifs',
        'av_condt' => 'Avances conditionnées',
        'prov_risques' => 'Provisions pour risques',
        'prov_charges' => 'Provisions pour charges',
        'emp_oblig_conv' => 'Emprunts obligatoires convertibles',
        'autres_emp_oblig' => 'Autres emprunts obligatoires',
        'emprunt_etab_credit' => 'Emprunts et dettes auprès des établissements de crédit',
        'dette_fi_div' => 'Emprunt et dettes financières divers',
        'avac_rec_comm' => 'Avances et acomptes reçus sur commandes en cours',
        'dette_fourn' => 'Dettes fournisseurs et comptes rattachés',
        'dette_fisc' => 'Dettes fiscales et sociales',
        'dette_immo' => 'Dettes sur immobilisations et comptes rattachés',
        'autres_dettes' => 'Autres dettes',
        'prod_ca' => 'Produits constatés d\'avance',
        'ecart_conv_pass' => 'Ecarts de conversion passif',

    ],

    'cr_fields' => [
        'ventes_march' => 'Ventes de marchandises',
        'prod_vendue_biens' => 'Production vendue biens',
        'prod_vendue_services' => 'Production vendue services',
        'prod_stock' => 'Production stockée',
        'prod_imm' => 'Production immobilisée',
        'sub_exploit' => 'Subvention d\'exploitation',
        'reprise_amo_prov' => 'Reprise sur amortissements et provisions, transfert de charges',
        'autres_prod' => 'Autres produits',
        'achats_march' => 'Achats de marchandises',
        'var_stock_march' => 'Variation de stock (marchandises)',
        'achats_mp' => 'Achats de matières premières et autres approvisionnements',
        'var_stock_mp' => 'Variation de stock (matière première)',
        'autres_achats' => 'Autres achats et charges externes',
        'impots_taxes' => 'Impôts, taxes et versements assimilés',
        'salaires' => 'Salaires et traitement',
        'charges_soc' => 'Charges sociales',
        'dot_ex_imm_amo' => 'Dotations d\'exploitation sur immobilisation : dotation aux ammortissements',
        'dot_ex_imm_prov' => 'Dotations d\'exploitation sur immobilisation : dotation aux provisions',
        'dot_ex_ac' => 'Dotations d\'exploitation sur actif circulant : dotations aux provisions',
        'dot_ex_risques' => 'Dotations d\'exploitation pour risques et charges : dotations aux provisions',
        'autres_charges' => 'Autres charges',
        'benef_att' => 'Bénéfice attribué ou perte transférée',
        'pertes_supp' => 'Perte supportée ou bénéfice transféré',
        'prod_fi_part' => 'Produits financiers de participations',
        'prod_autres_valmob' => 'Produits des autres valeurs mobilières et créances de l\'actif immobilisé',
        'autres_int' => 'Autres intérêts et produits assimilés',
        'prod_fi_reprise_prov' => 'Reprise sur provisions et transferts de charges',
        'diff_pos_change' => 'Différences positives de change',
        'prod_net_cession_valmob' => 'Produits nets sur cessions de valeurs mobilières de placement',
        'dot_fi_amo_prov' => 'Dotations financières aux amortissements et provisions',
        'interets' => 'Intérêts et charges assimilées',
        'diff_neg_change' => 'Différences négatives de change',
        'charges_net_cession_valmob' => 'Charges nettes sur cessions de valeurs mobilières de placement',
        'prod_excep_gest' => 'Produits exceptionnels sur opérations de gestion',
        'prod_excep_cap' => 'Produits exceptionnels sur opérations en capital',
        'prod_excep_reprise_prov' => 'Reprise sur provisions et transferts de charges',
        'charges_excep_gestion' => 'Charges exceptionnelles sur opérations de gestion',
        'chagres_excep_cap' => 'Charges exceptionnelles sur opérations en capital',
        'dot_excep_amo' => 'Dotations exceptionnelles aux amortissements et provisions',
        'part_sal' => 'Participation des salariés aux résultats de l\'entreprise',
        'impots_benef' => 'Impôts sur les bénéfices',
    ],

    'bilan_ss_tot' => [
        //Actif
        'imm_inco' => ['frais_etab','frais_dev','concess','fds_comm','autres_imm_inco','avac_imm_inco'],
        'imm_co' => ['terrains', 'construc', 'mat_indus', 'autres_imm_co', 'imm_en_cours', 'avac_imm_co'],
        'imm_fi' => ['part_equiv', 'autres_part', 'creances_part', 'autres_titres_imm', 'prets', 'autres_imm_fi'],
        'actif_imm' => ['imm_inco', 'imm_co', 'imm_fi'],
        'stocks' => ['mp_appro', 'encours_prod_biens', 'encours_prod_services', 'prod_interm_fin', 'marchand'],
        'creances' => ['creances_clients', 'autres_creances', 'cap_sous_a_nv'],
        'creances_exploit' => ['avac_comm', 'creances'],
        'actif_circ_exploit' => ['stocks', 'creances_exploit'],
        'ac_div' => ['val_mob', 'dispo'],
        'actif_circ' => ['actif_circ_exploit', 'ac_div'],
        'comptes_regul' => ['charges_ca', 'frais_emm_emp_et', 'primes_remb_oblig','ecart_conv_actif'],
        'actif' => ['actif_imm', 'actif_circ', 'comptes_regul'],
        //Passif
        'capitaux_propres' => ['cap_soc_indiv', 'primes_fus_emm_ap', 'ecart_reeval','res_leg', 'res_stat_contract', 'res_reg', 'autres_res', 'report_anouv', 'result_ex', 'sub_invest', 'prov_reg'],
        'autres_fds_propres' => ['prod_emm_part','av_condt'],
        'prov_rc' => ['prov_risques','prov_charges'],
        'dettes_fi' => ['emp_oblig_conv', 'autres_emp_oblig', 'emprunt_etab_credit', 'dette_fi_div'],
        'dettes_exploit' => ['avac_rec_comm', 'dette_fourn', 'dette_fisc', 'dette_immo', 'autres_dettes'],
        'dettes' => ['dettes_fi', 'dettes_exploit'],
        'tot_4' => ['dettes', 'prod_ca'],
        'passif' => ['capitaux_propres', 'autres_fds_propres', 'prov_rc', 'tot_4', 'ecart_conv_pass'],

    ],

    'cr_ss_tot' => [
        'CAnet' => ['ventes_march', 'prod_vendue_biens', 'prod_vendue_services'],
        'prod_exploit' => ['CAnet', 'prod_stock', 'prod_imm', 'sub_exploit', 'reprise_amo_prov', 'autres_prod'],
        'dot_exploit' => ['dot_ex_imm_amo', 'dot_ex_imm_prov', 'dot_ex_ac', 'dot_ex_risques'],
        'personnel' => ['salaires', 'charges_soc'],
        'charges_exploit' => ['achats_march', 'var_stock_march', 'achats_mp', 'var_stock_mp', 'autres_achats', 'impots_taxes', 'personnel', 'dot_exploit', 'autres_charges'],
        'op_commun' => ['benef_att', 'pertes_supp'],
        'prod_fi' => ['prod_fi_part', 'prod_autres_valmob', 'autres_int', 'prod_fi_reprise_prov', 'diff_pos_change', 'prod_net_cession_valmob'],
        'charges_fi' => ['dot_fi_amo_prov', 'interets', 'diff_neg_change', 'charges_net_cession_valmob'],
        'prod_excep' => ['prod_excep_gest', 'prod_excep_cap','prod_excep_reprise_prov'],
        'charges_excep' => ['charges_excep_gestion', 'chagres_excep_cap', 'dot_excep_amo'],
        'prod' => ['prod_exploit', 'benef_att', 'prod_fi', 'prod_excep'],
        'charges' => ['charges_exploit', 'pertes_supp', 'charges_fi', 'charges_excep', 'part_sal', 'impots_benef'],
    ],

];
